#Site settings
title: Club de Informática Marcos Frechín
remote_theme: chrisrhymes/bulma-clean-theme
permalink: pretty

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

livereload: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
      hero_image: /img/hero_main.jpg